server:
  port: 8081

services:
  the-movie-db-api:
    url: https://api.themoviedb.org/3/movie/top_rated
    apiKey: 217447754cf3b1c9bcc2b405edb96b7d
    language: pt-BR
  weather-api:
    url: https://api.openweathermap.org/data/2.5/weather
    appId: 99ae411ab1917a4864fa14a72ba2af32
    units: metric
    lang: pt_br


spring:
  datasource:
    url: jdbc:h2:mem:the-movies-db
    driver-class-name: org.h2.Driver
    username: test
    password:

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher